<% if @subtask.errors.any? %>
<div class="alert alert-secondary">
<%= @subtask.errors.count %>件エラーが発生しました。以下ご確認お願いいたします。
  <ul>
    <% @subtask.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_with model: @subtask, url: task_subtasks_path(@task.id), id: "subtaskForm", local: true do |f| %>
  <div id="subtaskContent">
    <%= f.label :サブタスク %>
    <%= f.text_area :subtask_content, autofocus: true, class: "form-control", id: "subtask_content" %>
  </div>
  <div id="taskSubmit" class="actions mt-4">
    <%= f.submit "投稿", class: "btn btn-outline-secondary btn-block", id: "subtask_submit" %>
  </div>
<% end %>

<!--JavaScriptで動的なバリデーション（リアルタイムでチェック）-->
<%= render "form_validation" %>